apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-app
spec:
  serviceName: "sample-app"
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image:  quay.io/rebontadeb/training/my-sample-app:v1  
