---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-clusterip
spec:
  type: ClusterIP
  selector:
    app: sample-app-nginx
  ports:
  - port: 18080
    targetPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: sample-app-nodeport
spec:
  type: NodePort
  selector:
    app: sample-app-nginx
  ports:
  - port: 18080
    targetPort: 80
    nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: sample-app-nginx
  ports:
  - port: 18080
    targetPort: 80
