apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-nginx
spec:
  selector:
    matchLabels:
      app: sample-app-nginx
  template:
    metadata:
      labels:
        app: sample-app-nginx
    spec:
      containers:
      - name: sample-app-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
